application:
  name: userservice
  message: Configured by Local Server
server:
  port: 8082
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users #your databse server here, keep /users
    username: root #your username here, probably username@dbserver required
    password: Juli2811! #your pw here
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
uuids:
  user-type: 
    volunteer: c1ee82fa-35d6-11ee-b0c3-d65d517f8931
    npo: d0f055d5-35d6-11ee-b0c3-d65d517f8931
    partner: d7755d26-35d6-11ee-b0c3-d65d517f8931
    group: cb7f53c5-35d6-11ee-b0c3-d65d517f8931
